# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dbWatcher.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "test.DbWatchRequest" do
  end
  add_message "test.DbEvent" do
    optional :action, :enum, 1, "test.DbAction"
    optional :person, :message, 2, "test.Person"
  end
  add_message "test.Person" do
    optional :id, :string, 1
    optional :name, :string, 2
    optional :email, :string, 3
  end
  add_enum "test.DbAction" do
    value :UPDATE, 0
    value :VIEW, 1
    value :CREATE, 2
    value :DELETE, 3
  end
end

module Test
  DbWatchRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.DbWatchRequest").msgclass
  DbEvent = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.DbEvent").msgclass
  Person = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.Person").msgclass
  DbAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.DbAction").enummodule
end
